name: Check Push

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Set up JDK
        uses: actions/setup-java@v4.2.2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload apk
        uses: actions/upload-artifact@v4.3.6
        with:
          name: OpenCvTest.apk
          path: app/build/outputs/apk/debug/app-debug.apk

  test:
    name: Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

  release:
    name: Release
    needs: test
    runs-on: ubuntu-latest
    permissions:
        contents: write
        pull-requests: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: OpenCvTest.apk
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: app/build/outputs/apk/debug/app-debug.apk
          tag_name: Release_v${{github.run_number}}

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}