name: Check Push

on:
  push:
    branches:
      - main 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Set up JDK 1.8
        uses: actions/setup-java@v4.2.2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload apk
        uses: actions/upload-artifact@v4.3.6
        with:
          name: OpenCvTest.apk
          path: app/build/outputs/apk/debug/app-debug.apk

  test:
    name: Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

  release:
    name: Release
    needs: test
    runs-on: ubuntu-lastest
    permissions:
        contents: write
        pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Release
        if: github.event_name == 'push'
        uses: MateSousa/create-release@v0.0.1 # v0.0.1 is the latest version
        with:
          repo_owner: ${{ secrets.REPO_OWNER }}}
          repo_name: ${{ secrets.REPO_NAME }}}
          base_branch: ${{ secrets.BASE_BRANCH }}}
          target_branch: ${{ secrets.TARGET_BRANCH }}}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Bot running
        if: github.event_name == 'pull_request' || github.event_name == 'issue_comment'
        uses: MateSousa/create-release-bot@v0.0.1
        with:
          repo_owner: ${{ secrets.REPO_OWNER }}}
          repo_name: ${{ secrets.REPO_NAME }}}
          base_branch: ${{ secrets.BASE_BRANCH }}}
          target_branch: ${{ secrets.TARGET_BRANCH }}}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_event: ${{ toJson(github.event) }}